name: branch-2.4

on:
  push:
    branches:
    - branch-2.4
  pull_request:
    branches:
    - branch-2.4

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala: [ '2.11', '2.12' ]
        hadoop: [ 'hadoop-2.6', 'hadoop-2.7' ]
    name: Build Spark with Scala ${{ matrix.scala }} / Hadoop ${{ matrix.hadoop }}

    steps:
    - uses: actions/checkout@master
    # We split caches because GitHub Action Cache has a 400MB-size limit.
    - uses: actions/cache@v1
      with:
        path: build
        key: build-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          build-
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/com
        key: ${{ matrix.scala }}-${{ matrix.hadoop }}-maven-com-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.scala }}-${{ matrix.hadoop }}-maven-com-
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/org
        key: ${{ matrix.scala }}-${{ matrix.hadoop }}-maven-org-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ matrix.scala }}-${{ matrix.hadoop }}-maven-org-
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Change to Scala ${{ matrix.scala }}
      run: |
        dev/change-scala-version.sh ${{ matrix.scala }}
    - name: Build with Maven
      run: |
        export MAVEN_OPTS="-Xmx2g -XX:ReservedCodeCacheSize=512m -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN"
        export MAVEN_CLI_OPTS="--no-transfer-progress"
        mkdir -p ~/.m2
        ./build/mvn $MAVEN_CLI_OPTS -DskipTests -Pyarn -Pmesos -Pkubernetes -Phive -Phive-thriftserver -Pscala-${{ matrix.scala }} -P${{ matrix.hadoop }} -Phadoop-cloud install
        rm -rf ~/.m2/repository/org/apache/spark


  lint:
    runs-on: ubuntu-latest
    name: Linters (Java/Scala/Python), licenses, dependencies
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Scala
      run: ./dev/lint-scala
    - name: Java
      run: ./dev/lint-java
    - name: Python
      run: |
        pip install flake8 sphinx numpy
        ./dev/lint-python
    - name: License
      run: ./dev/check-license
    - name: Dependencies
      run: ./dev/test-dependencies.sh

  lintr:
    runs-on: ubuntu-latest
    name: Linter (R)
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - uses: r-lib/actions/setup-r@v1
      with:
        r-version: '3.6.2'
    - name: install lib
      run: |
        sudo apt-get install -y libcurl4-openssl-dev
    - name: install R packages
      run: |
        sudo Rscript -e "install.packages(c('curl', 'xml2', 'httr', 'devtools', 'testthat', 'knitr', 'rmarkdown', 'roxygen2', 'e1071', 'survival'), repos='https://cloud.r-project.org/')"
        sudo Rscript -e "devtools::install_github('jimhester/lintr@v2.0.0')"
    - name: package and install SparkR
      run: ./R/install-dev.sh
    - name: lint-r
      run: ./dev/lint-r
